name: Make helper containers
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Build AUR enabled Arch containers
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Generate version string
        id: versionstring
        run: echo "THIS_TAG=${{ env.TODAY }}.0.${{ github.run_number }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.THIS_TAG}`,
              sha: context.sha
            })
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build paru container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          target: build-helper-img
          push: true
          context: .
          build-args: |
            HELPER=paru
            AUR_USER=ab
          tags: |
            ghcr.io/lukas-heiligenbrunner/archlinux-aur:latest
            ghcr.io/lukas-heiligenbrunner/archlinux-aur:${{ env.THIS_TAG }}
            ghcr.io/lukas-heiligenbrunner/archlinux-aur:paru
            ghcr.io/lukas-heiligenbrunner/archlinux-aur:paru-${{ env.THIS_TAG }}
      -
        name: Build yay container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          target: build-helper-img
          push: true
          context: .
          build-args: |
            HELPER=yay
            AUR_USER=ab
          tags: |
            ghcr.io/lukas-heiligenbrunner/archlinux-aur:yay
            ghcr.io/lukas-heiligenbrunner/archlinux-aur:yay-${{ env.THIS_TAG }}
